### ISSUE TITLE
Pack Error

### ISSUE THREAD

**Issue by SummerGua** [ota-meshi/vuepress2-plugin-full-text-search#28]
1. I run `npm run build` and `npm pack`, a tgz file will be generated
2. Then I run `npm install` to install it and `npm run docs:dev`
3. Errors occur: 
```
> vuepress2-plugin-full-text-search-playground-for-2.0.0-beta.46@1.0.0 docs:dev
> vuepress dev docs --clean-cache

TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string or an instance of URL. Received undefined
    at new NodeError (node:internal/errors:372:5)
    at fileURLToPath (node:internal/url:1420:11)
    at Object.<anonymous> (C:\Users\sshu\Desktop\vuepress2-plugin-full-text-search\playground-for-2.0.0-beta.43\node_modules\vuepress2-plugin-full-text-search\lib\index.cjs:150:45)
    at Module._compile (node:internal/modules/cjs/loader:1105:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (C:\Users\sshu\Desktop\vuepress2-plugin-full-text-search\playground-for-2.0.0-beta.43\docs\.vuepress\config.js:11:14)
```

Then I try it in another project, this also happens. However, install it from online npm is ok. How can I solve this problem?

**Comment by ota-meshi** [comment]
I can't reproduce your problem.
If we build on Windows, can the build files be different? I don't have Windows so I can't check it.

**Comment by SummerGua** [comment]
> I can't reproduce your problem. If we build on Windows, can the build files be different? I don't have Windows so I can't check it.

I remove the plugin from the `package.json` and  remove the import, then `npm install`, then re-add it to the `package.json` and `npm install`. The error won't happen. Thanks.
